### PR TITLE
feat: Establish a standardized development environment to reduce the difficulty of setup

### LINKED ISSUE #8192: [Feature] Establish a standardized development environment to reduce the difficulty of setup
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a new developer, I want to quickly set up my development environment so that I can start working on projects without delays caused by configuration issues.

### Description

use containers to create a standardized development environment with smooth VSCode integration, achieved through devcontainers.

### Related issues

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TonyWu1995**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary

Use the devcontainer tool to establish a unified development environment to reduce the difficulty of setting up development environments.

### Does this close any open issues?
Closes #8192

### CODE REVIEW

**Comment by klesh** [comment]
Nice work.
Can you post some working screenshots for preview?
Thanks

**Comment by TonyWu1995** [comment]
> Nice work. Can you post some working screenshots for preview? Thanks

Here are three screenshots: one showing the container being created, one showing the container creation completed, and the last one showing the backend and frontend being started.

截圖 2024-11-20 下午1 02 35

截圖 2024-11-20 下午1 20 23

截圖 2024-11-20 下午1 29 41

**Review by klesh — APPROVED** [review]
LGTM

**Comment by ohjongsung** [comment]
@TonyWu1995 Could you explain how it was done when there's nothing mapped to the running process?
image

**Pull request merged**
