### PR TITLE
Added Scarf gateway to DevLake Docker Compose downloads

### PR DESCRIPTION
**Pull request by arjundevarajan**
⚠️ **Pre Checklist**
Please complete ALL items in this checklist, and remove before submitting

[ x ] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
[ x ] I have added relevant tests.
[ x ] I have added relevant documentation.
[ x ] I will add labels to the PR, such as pr-type/bug-fix, pr-type/feature-development, etc.

**Summary**
What does this PR do?
This PR updates the Merico DevLake Docker Compose configuration to fetch DevLake containers via a Scarf endpoint, so that DevLake maintainers can collect basic de-identified download and adoption metrics. It does not affect where the containers are being hosted, as Scarf is only redirecting traffic back to Docker Hub.

**Does this close any open issues?**
This does not close any open issues.

**Other Information**
This change was suggested by Merico and DevLake maintainers/team members in direct discussions, and is Scarf's first code contribution to DevLake! We have a separate PR up for the DevLake helm charts.

### CODE REVIEW

**Comment by hezyin** [comment]
@Startrekzky Let's consider scheduling this into v0.19.

**Comment by Startrekzky** [comment]
@hezyin v0.20 or later. 

Hi @arjundevarajan , I have two questions.
1. Is this only for image downloading metrics? What other stats can I see?
2. What else should we do after merging this PR and the PR in helm chart repo?

**Comment by arjundevarajan** [comment]
Hi @Startrekzky sure, happy to help answer. 

1) Scarf helps to collect with a variety of de-identified aggregate metrics: unique downloads, version distribution, device type distribution, method of installation, OS distribution, arch distribution, etc. Some further information can be found here: https://docs.scarf.sh/data-export/

2) After merging the two PRs, there's nothing else that needs to be done from a technical standpoint to start collecting data. This represents the simplest form of a Scarf integration, so it's possible that there are additional pieces of instrumentation that could be useful in the future, but for now this would be sufficient to collect some basic analytics.

**Comment by aviaviavi** [comment]
@ZhangNing10 Arjun is OOO today so filling in with the v.0.17.0 docker compose change as requested. Please let me know if anything else is needed there!

**Review by klesh — APPROVED** [review]

**Pull request merged**
