### PR TITLE
fix: add pagination to job_collector task

### PR DESCRIPTION
**Pull request by ClaudioMascaro**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
Add pagination in github_graphql job collector task.

### Does this close any open issues?
Closes https://github.com/apache/incubator-devlake/issues/8028

### Screenshots

We needed to extract data from a large and complex repository, which has over 30000 workflow runs, and some of that can have more than 200 job runs.

Whenever the Collect Job task started, It simply wouldn't finish the query in time, entering in the retry flow:

Screenshot from 2024-12-09 16-56-00

we have tried to reduce api timeout, but it would only increase the number of unsuccessful retries:

Screenshot from 2024-12-06 15-38-14

So, after implementing the solution, it would solve our case, and after 17 hours, it was able to collect all data:

image
(don't mind the log I added locally to debug)

image

as for comparison purposes, we have extracted data from a much less complex repository, which before the implementation, took the following time:

Screenshot from 2024-12-11 08-11-06

and, after bringing off the solution (of course, rerunning in hard refresh mode), there was no change in pipeline overall time:

Screenshot from 2024-12-11 08-18-53

### Other Information

Already merged on main branch, reopening as requested: https://github.com/apache/incubator-devlake/pull/8233#pullrequestreview-2497839137

### CODE REVIEW

**Comment by ClaudioMascaro** [comment]
@klesh

**Review by klesh — APPROVED** [review]

**Comment by klesh** [comment]
This looks good! Could you also update the end-to-end (e2e) test cases to reflect these changes? Thanks!

**Comment by ClaudioMascaro** [comment]
@klesh do you have any example on writing e2e test for Collector tasks? I couldn't find any practical approach to that. Also there are tests failing for jira plugin.

**Comment by klesh** [comment]
Yes, that's unexpected; collectors shouldn't impact e2e tests.

Further investigation revealed that PR #8223 introduced the error, which I've addressed in PR #8243.  Everything should be working correctly now.

My apologies for the inconvenience, and thank you for your contribution!

**Pull request merged**
