### PR TITLE
feat: updates backend to listen on both IPv4 and IPv6 addresses

### LINKED ISSUE #6991: [Feature][backend] Add capability of listening to IPv4 & IPv6 interfaces
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

Currently the backend is configured to listen on a specific IPv4 address (0.0.0.0) which limits its compatibility with IPv6-only environments and localhost connections via IPv6. This prevents DevLake to work in our AWS EKS environment that runs exclusively on IPv6

### Description

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wanis-fahmy**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
This PR updates the backend to use a more flexible approach for binding to network interfaces. Instead of explicitly specifying the IPv4 unspecified address (0.0.0.0), the server now listens on all available network interfaces by using ":". This change allows the server to accept connections via both IPv4 and IPv6 addresses, including localhost.

### Does this close any open issues?
Closes #6991

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by wanisfahmyDE** [comment]
cherry-picked for release 0.21 as well: https://github.com/apache/incubator-devlake/pull/6992

**Comment by klesh** [comment]
Thanks for your contribution.
Has it been tested yet?

**Comment by wanisfahmyDE** [comment]
Hey @klesh, Gin provides an example [here]( https://gin-gonic.com/docs/examples/custom-http-config/ ) and here is the official golang [docs](https://pkg.go.dev/net#Listen) mentioning the same. 

I also tested a standalone separate example with the same implementation against IPv4 & IPv6 envs and both worked fine. 

I am confident that this should work 🤞 however I have to say, I have a devlake related local dev issue that prevents me from testing this locally.

**Review by klesh — APPROVED** [review]

**Comment by klesh** [comment]
Thanks for the explanation.

**Pull request merged**
