### PR TITLE
feat(github\gitlab): doesn't init api client when re-transformating

### LINKED ISSUE #8004: [Feature][Runner] When a re-transformation is triggered,  pipeline runner doesn't need to connection to data source' API.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I use GitHub plugin, and sometimes I need re-transformate data.  IMO, it will make some operations between tool layer amd somain layerss data, and it will NOT trigger collectors.

So I think there is no need to keep network to data source's endpoint is connected.

But in fact, if you have no internet connections, you can not re-transformate data successfully.

I think it can be improved for a faster transformation and better user experience.

### Description

I hope re-transformation should works well if there is no internet connection.

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
Doesn't init api client when re-transformating

### Does this close any open issues?
Closes #8004
Related #8017

### Screenshots
Include any relevant screenshots here.

#### restransformation with new codes
image

#### no internet connection, it can still work
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by d4x1** [comment]
I hope it should be merged into v1.1.0 if possiable.

**Comment by d4x1** [comment]
There is a remaing task: try to re-transformate data without any internet connection.

**Comment by d4x1** [comment]
It works in gitlab too
image

**Review by klesh — APPROVED** [review]

**Comment by d4x1** [comment]
> There is a remaing task: try to re-transformate data without any internet connection.

solved.

**Pull request merged**
