### PR TITLE
fix: reference zentao instead of gitlab

### PR DESCRIPTION
**Pull request by magnusp**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
Two path specifications are clashing, where one of them obviously belongs to another devlake plugin. This PR fixes the zentao plugin documentation. Seems to have originated in #5604.

### CODE REVIEW

**Comment by magnusp** [comment]
I'm guessing @keon94 has a better idea of the typings than I do. I just changed what made most sense :)

**Review by klesh — APPROVED** [review]

**Comment by klesh** [comment]
Good catch. Thanks for your contribution.

**Comment by abeizn** [comment]
@magnusp Already effective in v1.0.0-beta6

**Comment by JoshuaPoddoku** [comment]
Hi @magnusp,

Thank you for your contribution! I'm Joshua Poddoku, Committer at Apache DevLake. We'd love for you to join our Slack community or DM me incase you've joined already: https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw. Could you please share your full name there? We want to recognize your efforts with a certificate of contribution.

Best,
Joshua

**Pull request merged**
