### PR TITLE
chore: bumps node to 18 in builder image and actions for config-ui

### LINKED ISSUE #6885: [Feature][config-ui] upgrades nodejs to 18
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a DevOps engineer, I want to build the config-ui against a supported LTS version of nodejs

### Description

to upgrade the config-ui to node 18 because node 16 deprecated and without active support

### Related issues

https://github.com/apache/incubator-devlake/pull/6884

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wanis-fahmy**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
This PR upgrades the config-ui to node 18 because node 16 deprecated and without active support

### Does this close any open issues?
Closes https://github.com/apache/incubator-devlake/issues/6885

### Screenshots
Include any relevant screenshots here.

### Other Information
I built the config-ui ldocker image locally against node 18 and it was successful.

### CODE REVIEW

**Comment by wanisfahmyDE** [comment]
hey @Startrekzky, can you maybe have a look?
It's my first PR here, I hope I didn't miss something.
Thanks

**Review by klesh — APPROVED** [review]
LGTM

**Comment by klesh** [comment]
Thanks for your contribution.

**Comment by wanisfahmyDE** [comment]
thank you @klesh for reviewing 🙏

**Pull request merged**
