### PR TITLE
Add missing migration script to register.go

### LINKED ISSUE #8177: [Bug][Jira] Migration script not added to register.go
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Add missing migration script for `issues` table to register.go. 
... continuation on #7885

### What do you expect to happen

migration script to be added to register.go so that it's executed when Devlake is started

### How to reproduce

.

### Anything else

_No response_

### Version

v1.0.2-beta3@7cf1a60

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sstojak1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
Adds increaseProjectKeyLength and changeIssueComponentType to register.go

### Does this close any open issues?
Closes [#8177](https://github.com/apache/incubator-devlake/issues/8177)

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Review by klesh — DISMISSED** [review]
Good catch, thanks for your contribution.

**Comment by sstojak1** [comment]
@klesh can we merge it?

**Comment by klesh** [comment]
@sstojak1 Could you fix the test cases?

**Comment by sstojak1** [comment]
@klesh, 20240813_change_issue_component_type is fixed. Could you run the tests again?

Before that, could you review the 20240813_increase_project_key_length script? It might fail since the project_key column doesn’t exist in cq_projects. Did you intend to modify a different column?

**Comment by klesh** [comment]
@sstojak1 I just checked the code and found out `20240813_increase_project_key_length` under the `core/model` should be changing the length of `cq_projects.id` from 255 to 500 instead. 
Would you kindly update the script to do so? Thanks, 🌹

**Comment by sstojak1** [comment]
@klesh updated...

**Comment by klesh** [comment]
@sstojak1 Thank you very much for correcting my mistakes 🌹
I wondered why people kept reporting "Data too long" after my PR merged.

**Comment by sstojak1** [comment]
I was almost one of them until I did a bit of troubleshooting 😅

**Review by klesh — APPROVED** [review]
LGTM

**Pull request merged**
