### PR TITLE
feat(logger): remove x-cray/logrus-prefixed-formatter

### LINKED ISSUE #5666: [Feature][Backend] log with line number
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As s developer, sometimes I need to trace devlake backend API's logs or debug some errors,  the logrus now only prints messages without line number. We have to search the message and it's not convenient.

According to [logrus](https://github.com/sirupsen/logrus)'s readme, it supports log with line numbers using thrid party formatter or just set `SetReportCaller(true)`.

It will be helpful if all log messager have line numbers.

### Description

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?

Fix #5666 

### Does this close any open issues?
Closes #5666 

### Screenshots
Include any relevant screenshots here.
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by d4x1** [comment]
Before
```time="2023-07-18 18:24:41" level=info msg=xxx```
After
```time="2023-07-18 18:26:09" level=info msg=xxx  func="github.com/apache/incubator-devlake/impls/logruslog.(*DefaultLogger).Log"  file="/Users/username/Code/go/src/github.com/merico-dev/lake/backend/impls/logruslog/logger.go:58"```


cc @ZhangNing10

**Comment by klesh** [comment]
@d4x1 Is the func/file always pointing to the logruslog logger?

**Comment by d4x1** [comment]
> 

I have searched this repo, only logrus was found, all logger is inited in  package logruslog.

And I run the devlake backend, logger in handlers and plugins are both worked as expected.

**Review by keon94 — DISMISSED** [review]
LGTM

**Comment by keon94** [comment]
@d4x1 Please run `go mod tidy` in backend/ to get rid of `github.com/x-cray/logrus-prefixed-formatter`  from the dependency list.

**Comment by d4x1** [comment]
Please don't merge this PR, I find the line number is always `backend/impls/logruslog/logger.go:58`, it needs a further update.

**Review by klesh — APPROVED** [review]

**Pull request merged**
