### PR TITLE
pr-type/bug-fix 7100 fixed by adding auto-discovery of interface type (ipv4/ipv6) inside nginx container

### LINKED ISSUE #7100: [Bug][config-ui] Allow NOT to not be forced to use ipV6
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When https://github.com/apache/incubator-devlake/issues/6954 was merged, ipv6 was enabled in nginx, however the side-effect was to break the container if ipv6 is not enabled. config-ui container does not start if ipv6 is disabled. Get error:

```
2024/03/04 18:20:37 [emerg] 11#11: socket() [::]:4000 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:4000 failed (97: Address family not supported by protocol)
```

### What do you expect to happen

Container to run, with only ipv4 enabled

### How to reproduce

Run config-ui container on a host without ipv6 stack enabled.

### Anything else

Ideally it would be an optional thing.

### Version

release-v0.21_240301_0901_460517a

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ivansumak**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [/] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [/] I have added relevant tests.
- [/] I have added relevant documentation.
- [/] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
Due to the bug described in #7100, config-ui nginx container will start only on dual-stack IP environments. This PR adds auto-discovery of interface type to nginx container and configures the nginx listener(s) accordingly. 

### Does this close any open issues?
Closes #7100 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by klesh** [comment]
Nice work.  Looking good to me. Was it tested?

**Comment by ivansumak** [comment]
> Nice work. Looking good to me. Was it tested?

Yes, I tested it both in dual-stack and IPv4 only environments.

**Review by klesh — APPROVED** [review]

**Comment by klesh** [comment]
Thanks for you contribution.

**Comment by JoshuaPoddoku** [comment]
Hi @ivansumak,

Thank you for your contribution! I'm Joshua Poddoku, a committer at Apache DevLake. We'd love for you to join our Slack community or DM me incase you've joined already: https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw. Could you please share your full name there? We want to recognize your efforts with a certificate of contribution.

Best,
Joshua Poddoku
Committer

**Pull request merged**
