### PR TITLE
fix: swag doc 500 / PLUGIN option not working

### PR DESCRIPTION
**Pull request by klesh**
### Summary
Fix the following error:
image

Plus, also fix the `PLUGIN` EnvVar for generating doc for given plugins only was not working, note that the EnvVar was renamed to `DEVLAKE_PLUGINS`

### CODE REVIEW

**Comment by klesh** [comment]
FYI @keon94 @CamilleTeruel @leric we are rename the `PLUGIN` environment variable for selective plugin compilation to `DEVLAKE_PLUGINS` to avoid conflict and better security.

**Review by abeizn — APPROVED** [review]

**Comment by mieliespoor** [comment]
@klesh this results in a build failure. I see the same for me locally

https://github.com/apache/incubator-devlake/actions/runs/6665034813/job/18113840200#step:8:502
```
#33 217.5 scripts/swag.sh
#33 217.5 fatal: not a git repository (or any of the parent directories): .git
#33 217.6 .
```

**Comment by mieliespoor** [comment]
@klesh / @abeizn  this results in a build failure. I see the same for me locally

https://github.com/apache/incubator-devlake/actions/runs/6665034813/job/18113840200#step:8:502

```
#33 217.5 scripts/swag.sh
#33 217.5 fatal: not a git repository (or any of the parent directories): .git
#33 217.6 .
```

**Comment by klesh** [comment]
> @klesh / @abeizn this results in a build failure. I see the same for me locally
> 
> https://github.com/apache/incubator-devlake/actions/runs/6665034813/job/18113840200#step:8:502
> 
> ```
> #33 217.5 scripts/swag.sh
> #33 217.5 fatal: not a git repository (or any of the parent directories): .git
> #33 217.6 .
> ```

Thanks for the heads up, will look into it asap

**Comment by klesh** [comment]
> @klesh / @abeizn this results in a build failure. I see the same for me locally
> 
> https://github.com/apache/incubator-devlake/actions/runs/6665034813/job/18113840200#step:8:502
> 
> ```
> #33 217.5 scripts/swag.sh
> #33 217.5 fatal: not a git repository (or any of the parent directories): .git
> #33 217.6 .
> ```

Thanks for the heads up, will look into it asap

**Pull request merged**
