### PR TITLE
refactor: hudson.maven.MavenModuleSet is now treated as a scope

### LINKED ISSUE #7598: [Bug][Jenkins] MavenModuleSet should be treated as a scope
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The logic for categorizing Devlake Remote Scopes has [changed](https://github.com/apache/incubator-devlake/pull/7213/files#diff-ef2d9899f5788356b03b7c5c1320ad5bb7e78aa63047d202cde86ed1360bd7ab) in version v1.0.0-beta5. Previously, the default category was "scope," but now it is "group." This change has led to issues, such as `hudson.maven.MavenModuleSet` Jenkins project type being treated as a group instead of a scope. As a result, you cannot add a new Devlake Remote Scope because it's incorrectly categorized as a group.

### What do you expect to happen

I expect that `hudson.maven.MavenModuleSet` Jenkins project is not categorized as group by Devlake

### How to reproduce

Create a new Maven Project in Jenkins and try to add it through Devlake:
image

### Anything else

_No response_

### Version

v1.0.0-beta11

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by sstojak1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [ ] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [ ] I have added relevant tests.
- [ ] I have added relevant documentation.
- [ ] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
`hudson.maven.MavenModuleSet` Jenkins pipeline will now be treated as a scope

### Does this close any open issues?
Closes [7598](https://github.com/apache/incubator-devlake/issues/7598)

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by d4x1** [comment]
@sstojak1  Have you tested it ?  And it works as expected?

**Comment by klesh** [comment]
Looks good to me in terms of a fix.
I wonder if it would make more sense to make `scope` the default? That is, to only match for groups and let the others be `scope` by default?

**Comment by klesh** [comment]
@sstojak1 BTW, are you interested in joining Apache as a Committer? I would like to invite you if you are up for it. Please reach me out on Slack if you do, my name is "Klesh Wong" on the channel.

**Comment by sstojak1** [comment]
@klesh makes sense to have scope as a default since there should be more jobs that should be treated as `scope` then `group`.
I've tweaked the logic a bit by blending the new and old approaches. Please review. 
`WorkflowMultiBranchProject` is unique—it has jobs but should be considered as 'scope', hence the extra check in isGroup.

**Comment by klesh** [comment]
@gustavobini Would you like to take a look at the code? Thanks in advance.

**Review by klesh — APPROVED** [review]

**Comment by klesh** [comment]
Thank you all.

**Pull request merged**
